config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get '/', to:'tops#index'
  resources :staffs do
    collection do
      post :confirm
   end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]
  get '/sessions',to:'sessions#new'
if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :staff
end

app/models/staff.rb
class Staff < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :staff_tel, presence: true, length: { maximum: 13 },
                    format: { with: /\A[0-9]+-[0-9]+-[0-9]+\z/i }
    validates :cheo_id, presence: true, length: { maximum: 13 },
                    format: { with: /\A[a-z0-9]+\z/i }
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :staffs, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_staff, through: :favorites ,source: :staff
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit,:update,:destroy,:show]
  before_action :login_check, only: [:new,:edit, :show]
  
  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path
  end
  
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      ContactMailer.contact_mail(@blog).deliver
      redirect_to blogs_path
      else
      render 'new'
    end
  end

  def show
     @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path
    else
      render 'edit'
    end
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    render :new if @blog.invalid?
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :image, :image_cache,
                                 :password_confirmation)
  end
    def blog_params
      params.require(:blog).permit(:title, :content, :image, :image_cache)
    end

    # idをキーとして値を取得するメソッド
    def set_blog
      @blog = Blog.find(params[:id])
    end

  def login_check
    unless current_user
      redirect_to new_session_path
    end

  def contact_params
      params.require(:contact).permit(:name, :email, :content, :image, :image_cache)
  end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(staff_id: params[:staff_id])
    redirect_to staffs_url, notice: "#{favorite.staff.staff_name}をよく使う連絡先に登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to staffs_url, notice: "#{favorite.staff.staff_name}をよく使う連絡先から解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to staffs_path
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:edit,:update,:destroy,:show]
  before_action :login_check, only: [:new,:edit, :show]
  
  def index
    #@staffs = Staff.all
    @search = Staff.search(params[:q]) # この行を追加
    @staffs = @search.result #この行を修正
  end

  def new
    if params[:back]
      @staff = Staff.new(staff_params)
    else
      @staff = Staff.new
    end
  end
  
  def destroy
    @staff.destroy
    redirect_to staffs_path
  end
  
  def create
    @staff = Staff.new(staff_params)
    @staff.user_id = current_user.id
    if @staff.save
      #ContactMailer.contact_mail(@staff).deliver
      redirect_to staffs_path
      else
      render 'new'
    end
  end

  def show
     @favorite = current_user.favorites.find_by(staff_id: @staff.id)
  end

  def edit
  end

  def update
    if @staff.update(staff_params)
      redirect_to staffs_path
    else
      render 'edit'
    end
  end

  def confirm
    @staff = Staff.new(staff_params)
    @staff.user_id = current_user.id
    render :new if @staff.invalid?
  end

  def import
    Staff.import(params[:file])
    redirect_to "/staff"
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :image, :image_cache,
                                 :password_confirmation)
  end
    def staff_params
      params.require(:staff).permit(:staff_name, :cheo_id, :staff_tel, :staff_add, :skill_biz01, :skill_biz02,
                                    :skill_con01, :skill_con02, :skill_other, :image, :image_cache)
    end

    def set_staff
      @staff = Staff.find(params[:id])
    end

  def login_check
    unless current_user
      redirect_to new_session_path
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @favorites_staff = @user.favorite_staff
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to sessions_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image, :image_cache, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StaffSearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <ul>
      <li class="homeBtn"><a href="/">HOME</a></li>
      <% if logged_in? %>
      <li><%=link_to "スタッフ一覧",staffs_path %></li>
      <li><%= link_to "個人ページ", user_path(current_user.id) %></li>
      <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
       <% else %>
      <li><%= link_to "アカウント登録", new_user_path %></li>
      <% end %>
    </ul>
  </header>

      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key} message") %>
      <% end %>

      <%= yield %>

  <footer>
    <p>201801期 Mizutani Eiji　2018 Copyright NTT ComCheo Corp.</p>
  </footer>

</body>
</html>

app/views/layouts/application.html0.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionLogin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/staffs/_form.html.erb
<%= form_with(model: @staff, local: true ,url: confirm_staffs_path ) do |form| %>
<p><%= notice %></p>

        <% @staff.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

<div>
<table>
  <tr>
    <td><%= form.label :staff_name ,"スタッフ名" %></td>
    <td colspan="5"><%= form.text_field :staff_name %></td>
  </tr>
  
  <tr>
    <td><%= form.label :cheo_id ,"スタッフID" %></td>
    <td colspan="5"><%= form.text_field :cheo_id %></td>
  </tr>

  <tr>
    <td><%= form.label :staff_tel, "携帯番号" %></td>
    <td colspan="5"><%= form.text_field :staff_tel %></td>
  </tr>

  <tr>
    <td><%= form.label :staff_add, "住所" %></td>
    <td colspan="5"><%= form.text_field :staff_add %></td>
  </tr>

  <tr>
    <td><%= form.label :skill_biz01, "対応スキル" %></td>
    <td><%= hidden_field_tag 'staff[skill_biz01]', 'なし' %>
　　    <%= check_box_tag 'staff[skill_biz01]', 'あり'  %>法人01</td>

    <td><%= hidden_field_tag 'staff[skill_biz02]', 'なし' %>
　　    <%= check_box_tag 'staff[skill_biz02]', 'あり'  %>法人02</td>

    <td><%= hidden_field_tag 'staff[skill_con01]', 'なし' %>
　　    <%= check_box_tag 'staff[skill_con01]', 'あり'  %>個人01</td>

    <td><%= hidden_field_tag 'staff[skill_con02]', 'なし' %>
　　    <%= check_box_tag 'staff[skill_con02]', 'あり'  %>個人02</td>

    <td><%= hidden_field_tag 'staff[skill_other]', 'なし' %>
　　    <%= check_box_tag 'staff[skill_other]', 'あり'  %>特殊案件</td>
  </tr>

  <tr>
    <td><%= form.label :image,  "スタッフ写真" %></td>
    <td colspan="5"><center><%= form.file_field :image, id: :staff_image %></center></td>
  </tr>

  <tr>
    <td colspan="6"><button type="submit" class="btn btn-default">送 信</button></td>
  </tr>
  </table>
  </div>
<% end %>

app/views/staffs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<div class="container">
   <div class="staff-details">

<%= form_with(model: @staff, url: staffs_path, local: true) do |form| %>

  <%= form.hidden_field :staff_name %>
  <%= form.hidden_field :cheo_id %>
  <%= form.hidden_field :staff_tel %>
  <%= form.hidden_field :staff_add %>
  <%= form.hidden_field :skill_biz01 %>
  <%= form.hidden_field :skill_biz02 %>
  <%= form.hidden_field :skill_con01 %>
  <%= form.hidden_field :skill_con02 %>
  <%= form.hidden_field :skill_other %>
 <div class="staff_title">
<div>
<table>
  <p><%= image_tag(@staff.image) %></p>
  <%= form.hidden_field :image_cache %>
  <tr>
    <td>スタッフ名</td>
    <td colspan="5"><%= @staff.staff_name %></td>
  </tr>
  
  <tr>
    <td>スタッフID</td>
    <td colspan="5"><%= @staff.cheo_id %></td>
  </tr>

  <tr>
    <td>携帯番号</td>
    <td colspan="5"><%= @staff.staff_tel %></td>
  </tr>

  <tr>
    <td>住所</td>
    <td colspan="5"><%= @staff.staff_add %></td>
  </tr>

  <tr>
    <td>対応スキル</td>
    <td>法人01：<%= @staff.skill_biz01 %></td>
    <td>法人02：<%= @staff.skill_biz02 %></td>
    <td>個人01：<%= @staff.skill_con01 %></td>
    <td>個人02：<%= @staff.skill_con02 %></td>
    <td>特殊案件：<%= @staff.skill_other %></td>
  </tr>
  
  <tr>
    <td colspan="6"><button type="submit" class="btn btn-default">登録する</button></td>
  </tr>
<% end %>
</table>
</div>
  <%= form_with(model: @staff, url: new_staff_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :staff_name %>
  <%= form.hidden_field :cheo_id %>
  <%= form.hidden_field :staff_tel %>
  <%= form.hidden_field :staff_add %>
  <%= form.hidden_field :skill_biz01 %>
  <%= form.hidden_field :skill_biz02 %>
  <%= form.hidden_field :skill_con01 %>
  <%= form.hidden_field :skill_con02 %>
  <%= form.hidden_field :skill_other %>
  <button type="submit" class="btn btn-default">戻る</button>
<% end %>
   </div>
   </div>
</div>

app/views/staffs/edit.html.erb
<h1>スタッフ情報編集</h1>
<div class="container">
   <div class="staff-details">

<%= form_with(model: @staff, local: true) do |form| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= @staff.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @staff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div>
<table>
  <tr>
    <td><%= form.label :staff_name ,"スタッフ名" %></td>
    <td colspan="5"><%= form.text_field :staff_name %></td>
  </tr>
  
  <tr>
    <td><%= form.label :cheo_id ,"スタッフID" %></td>
    <td colspan="5"><%= form.text_field :cheo_id %></td>
  </tr>

  <tr>
    <td><%= form.label :staff_tel, "携帯番号" %></td>
    <td colspan="5"><%= form.text_field :staff_tel %></td>
  </tr>

  <tr>
    <td><%= form.label :staff_add, "住所" %></td>
    <td colspan="5"><%= form.text_field :staff_add %></td>
  </tr>

  <tr>
    <td><%= form.label :skill_biz01, "対応スキル" %></td>
    <td><%= hidden_field_tag 'staff[skill_biz01]', 'なし' %>
　　    <%= check_box_tag 'staff[skill_biz01]', 'あり'  %>法人01</td>

    <td><%= hidden_field_tag 'staff[skill_biz02]', 'なし' %>
　　    <%= check_box_tag 'staff[skill_biz02]', 'あり'  %>法人02</td>

    <td><%= hidden_field_tag 'staff[skill_con01]', 'なし' %>
　　    <%= check_box_tag 'staff[skill_con01]', 'あり'  %>個人01</td>

    <td><%= hidden_field_tag 'staff[skill_con02]', 'なし' %>
　　    <%= check_box_tag 'staff[skill_con02]', 'あり'  %>個人02</td>

    <td><%= hidden_field_tag 'staff[skill_other]', 'なし' %>
　　    <%= check_box_tag 'staff[skill_other]', 'あり'  %>特殊案件</td>
  </tr>

  <tr>
    <td><%= form.label :image %></td>
    <td colspan="5"><center><%= form.file_field :image, id: :image %></center></td>
  </tr>

  <tr>
    <td colspan="6"><button type="submit" class="btn btn-default">送信</button></td>
  </tr>
  </table>
  </div>

<% end %>
</div>
</div>

   <div class="staff-links">
     <%= link_to '一覧へ戻る', staffs_path, class: 'btn btn-default' %>
   </div>

app/views/staffs/index.html.erb
<h1>スタッフ一覧</h1>

<div class="container">
  <div id="new-staff-link">
    <%= link_to '新規スタッフ登録', new_staff_path, class: 'btn btn-default' %>
  </div>
    <br />
  <%= search_form_for @search do |f| %>
  <%= f.label :staff_name_cont, 'スタッフ名' %>
  <%= f.text_field :staff_name_cont %>
  <%= f.label :staff_add_cont, '住所' %>
  <%= f.text_field :staff_add_cont %>
  <br />
  <%= f.label :skill_biz01_cont, '法人01' %>
  <%= f.check_box(:skill_biz01_cont,{:checked=>false},"あり","") %>
  <%= f.label :skill_biz02_cont, '法人02' %>
  <%= f.check_box(:skill_biz02_cont,{:checked=>false},"あり","") %>
  <%= f.label :skill_con01_cont, '個人01' %>
  <%= f.check_box(:skill_con01_cont,{:checked=>false},"あり","") %>
  <%= f.label :skill_con02_cont, '個人02' %>
  <%= f.check_box(:skill_con02_cont,{:checked=>false},"あり","") %>
  <%= f.label :skill_other_cont, '特殊案件' %>
  <%= f.check_box(:skill_other_cont,{:checked=>false},"あり","") %>
  <div>
    <%= f.submit '検索する' %>
  </div>
<% end %>
  <br />
  <div class="row">
    <% @staffs.each do |staff| %>
      <div class="col-xs-12 col-md-6 staff-panel">
        <div>
          <table border="1">
            
            <th><center>スタッフ名</center></th>
            <th><center>住所</center></th>
            <th colspan="3"><center>操作</center></th>
            
            <tr>
              <td width="100" height="20"><%= staff.staff_name %></td>
              <td width="200" height="20"><%= staff.staff_add %></td>
              <div class="staff-links">
                <td><%= link_to '詳細', staff, class: 'btn btn-default' %></td>
                <td><%= link_to '編集', edit_staff_path(staff), class: 'btn btn-info' %></td>
                <td><%= link_to '削除', staff, method: :delete, data: { confirm: '本当に削除しますか' }, class: 'btn btn-danger' %></td>

            <tr>
              </div>
          </table>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/staffs/new.html.erb
  <h2>スタッフ新規登録</h2>
<div class="container">
   <div class="staff-details">
  <%= render 'form' %>
  
     </div>

   <div class="staff-links">
     <%= link_to '一覧へ戻る', staffs_path, class: 'btn btn-default' %>
   </div>
</div>

app/views/staffs/show.html.erb
<h1>スタッフ情報詳細</h1>
<div class="container">
   <div class="staff-details">
<div>
<table border="1">
  <p><%= image_tag(@staff.image) %></p>
  <tr>
    <td>スタッフ名</td>
    <td colspan="5"><%= @staff.staff_name %></td>
  </tr>
  
  <tr>
    <td>スタッフID</td>
    <td colspan="5"><%= @staff.cheo_id %></td>
  </tr>

  <tr>
    <td>携帯番号</td>
    <td colspan="5"><%= @staff.staff_tel %></td>
  </tr>

  <tr>
    <td>住所</td>
    <td colspan="5"><%= @staff.staff_add %></td>
  </tr>

  <tr>
    <td>対応スキル</td>
    <td>法人01：<%= @staff.skill_biz01 %></td>
    <td>法人02：<%= @staff.skill_biz02 %></td>
    <td>個人01：<%= @staff.skill_con01 %></td>
    <td>個人02：<%= @staff.skill_con02 %></td>
    <td>特殊案件：<%= @staff.skill_other %></td>
  </tr>
</table>
</div>

     <% if @staff.user == current_user %>
     <%= link_to '編集', edit_staff_path, class: 'btn btn-info' %>　
     <% end %>
   </div>

  <% if @favorite.present? %>
    <%= link_to 'よく使う連絡先から解除', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'よく使う連絡先に登録', favorites_path(staff_id: @staff.id), method: :post, class: 'btn btn-primary' %>
  <% end %>

   <div class="staff-links">
     <%= link_to '一覧へ戻る', staffs_path, class: 'btn btn-default' %>
   </div>
</div>

app/views/tops/index.html.erb
<h1>Staff Search ver3.0</h1>

<div class="container">
  <div class="row">


           <%= image_tag 'top.png' %>


    
    <div class="col-xs-12">
      <% if logged_in? %>
      <%=link_to 'スタッフ一覧', staffs_path, class: 'btn btn-default' %>
       <% else %>
      <%= link_to 'ログイン', sessions_path, class: 'btn btn-default' %>
      <% end %>
      </p>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>新規アカウント登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 件のエラーがあります。</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
    </ul>
  </div>
  <% end %>

        <%= form_with(model: @user, local: true) do |f| %>
    <div>
      <table>

          <tr>
            <td><%= f.label :name %></td>
            <td><%= f.text_field :name %></td>
          </tr>

          <tr>
            <td><%= f.label :email %></td>
            <td><%= f.email_field :email %></td>
          </tr>

          <tr>
            <td><%= f.label :password %></td>
            <td><%= f.password_field :password %></td>
          </tr>

          <tr>
            <td><%= f.label :password_confirmation %></td>
            <td><%= f.password_field :password_confirmation %></td>
          </tr>

          <tr>
            <td><%=f.label :image,"ユーザー画像" %></td>
            <td><%= f.file_field :image %></td>
          </tr>

          <tr>
            <td colspan="2"><%= f.submit "アカウント登録" %></td>
          </tr>
      </table>
    </div>
    <% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>の詳細画面</h1>

<p>メールアドレス: <%= @user.email %></p>


<div>
    <table border="1">
    <th><center>スタッフ名</center></th>
    <th><center>住所</center></th>
    <th><center>携帯番号</center></th>
    <% @favorites_staff.each do |staff| %>
    <tr>
    <td width="100" height="20"><%= link_to "#{staff.staff_name}",staff_path(staff.id) %></td>
    <td width="300" height="20"><%= "#{staff.staff_add}" %></td>
    <td width="200" height="20"><%= "#{staff.staff_tel}" %></td>
    </tr>
    <% end %>
    </table>
</div>